LDLIBS=-lGLEW -lGL -lglut -lm
bspline: recursive_bspline.c
	gcc recursive_bspline.c -o bspline $(LDLIBS)
work01: work01.c
	gcc work01.c -o work01 $(LDLIBS)
work02: work02.c
	gcc work02.c -o work02 $(LDLIBS)
